apiVersion: db.atlasgo.io/v1alpha1
kind: AtlasSchema
metadata:
  labels:
    app.kubernetes.io/name: atlasschema
    app.kubernetes.io/instance: atlasschema-sample
    app.kubernetes.io/part-of: atlas-operator
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/created-by: atlas-operator
  name: atlasschema-mysql
spec:
  urlFrom:
    secretKeyRef:
      key: url
      name: mysql-credentials
  policy:
    lint:
      destructive:
        error: true
    diff:
      skip:
        drop_column: true
  schema:
    sql: |
      create table users_2 (
        id int not null auto_increment,
        name varchar(255) not null,
        email varchar(255) unique not null,
        short_bio varchar(255) not null,
        primary key (id)
      );
  exclude:
    - ignore_me

