apiVersion: v2
name: atlas-operator
description: The Atlas Kubernetes Operator
type: application
version: 0.7.23
appVersion: 0.7.23
dependencies:
  - name: atlas-agent
    version: 0.38.1
    repository: oci://ghcr.io/ariga/charts
    condition: atlas-agent.enabled